spring:
  profiles:
    default: dev # (운영 환경에서는 SPRING_PROFILES_ACTIVE=prod로 주입)

logging:
  level:
    org.springframework.security: DEBUG

firebase:
  service-account-file: ${FIREBASE_SERVICE_ACCOUNT_FILE}
