spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao # 임시 리다이렉트 URI
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-seconds: 3600 # 1시간
  refresh-token-expiration-seconds: 1209600 # 14일