name: 🚀 Deploy
description: 배포 관련 이슈
title: "[Deploy] "
labels: ["deploy 🚀"]
body:
  - type: input
    id: version
    attributes:
      label: 📌 배포 버전
      placeholder: ex) v1.0.0
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: 📝 변경 사항 요약
      description: 이번 배포에 포함된 주요 변경점을 적어주세요.
      placeholder: ex) 회원가입 기능 추가 (#12), 로그인 에러 수정 (#34)
  - type: input
    id: date
    attributes:
      label: 📅 배포 일시
      placeholder: ex) 2025-08-17 18:00
  - type: textarea
    id: checklist
    attributes:
      label: ✅ 체크리스트
      description: 배포 전에 확인해야 할 사항
      placeholder: |
        - [ ] CI/CD 통과 확인
        - [ ] 환경 변수 최신화
        - [ ] 롤백 방법 확인